input: 'select',
            inputOptions: {
              WOKTEMP: '設置溫度',
              WOKOIL: '起鑊',
              POUROX : '倒盒',
              LOADBOX : '取盒',
              WAIT : '翻炒',
              POURFOOD: '上菜',
              WOKCLEAN: '洗鍋',
              WOKY :'設置轉速',
              END : '完成',
              INIT : '初始化',
              '調料': {
                'PSDS 0': '假的',
                'PSDS 1': '下糖',
                'PSDS 2': '下鹽',
                'PSDS 3': '下胡椒',
                'PSDS 4': '自定調料'
              },
              '液體': {
                'PLQS 0': '假的',
                'PLQS 1': '加水',
                'PLQS 2': '下油',
                'PLQS 3': '3號泵噴出',
                'PLQS 4': '4號泵噴出',
                'PLQS 5': '5號泵噴出',
                'PLQS 6': '芡汁',
                'PLQS 7': '7號泵噴出',
                'PLQS 8': '8號泵噴出',
              },